// Generated by CoffeeScript 1.12.2
(function() {
  var advanceChar, chooseStart, clockRunning, computeWPM, fastestTime, numberOfStartingLetters, qwerty, reset, start, started, stop, stoppedDuration, timeBegan, timeStopped, typedLetters, typedWrongLetters;

  qwerty = ["q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "a", "s", "d", "f", "g", "h", "j", "k", "l", "z", "x", "c", "v", "b", "n", "m"];

  numberOfStartingLetters = 0;

  typedLetters = 0;

  typedWrongLetters = 0;

  if ((Cookies.get("time") != null)) {
    fastestTime = Cookies.get("time");
  } else {
    fastestTime = "";
  }

  advanceChar = function(char) {
    var id, nextCharacter;
    nextCharacter = String.fromCharCode(char);
    id = "#" + qwerty[typedLetters + typedWrongLetters];
    console.log(id + nextCharacter);
    console.log(char);
    console.log(qwerty[typedLetters + typedWrongLetters].charCodeAt(0));
    if (char === qwerty[typedLetters + typedWrongLetters].charCodeAt(0)) {
      typedLetters++;
      $(id).addClass("correct");
    } else {
      typedWrongLetters++;
      $(id).addClass("wrong");
    }
    if (typedLetters === 26) {
      stop();
      if (numberOfStartingLetters === 0) {
        if (fastestTime.length !== 0) {
          fastestTime = Math.min(fastestTime, $("#time").text());
        } else {
          fastestTime = $("#time").text();
        }
        document.cookie = "time=" + fastestTime;
        $("#fastestTime").text(fastestTime);
      }
    }
    return $("#speed").text(computeWPM());
  };

  $(document).keypress(function(e) {
    if (e.which === 13) {
      return reset();
    } else if (typedLetters + typedWrongLetters === 26) {

    } else if (e.shiftKey) {
      return chooseStart(String.fromCharCode(e.which + 32));
    } else {
      if (typedLetters === 0) {
        reset();
        typedLetters = numberOfStartingLetters;
        start();
      }
      return advanceChar(e.which);
    }
  });

  $(document).keydown(function(e) {
    var idprev;
    if (e.keyCode === 8) {
      idprev = "#" + String.fromCharCode(typedLetters + typedWrongLetters + 96);
      if ($(idprev).hasClass("correct")) {
        $(idprev).removeClass("correct");
        return typedLetters--;
      } else if ($(idprev).hasClass("wrong")) {
        $(idprev).removeClass("wrong");
        return typedWrongLetters--;
      }
    }
  });

  $(function() {
    $("#reset").click(function() {
      return reset();
    });
    if (fastestTime.length === 0) {
      $("#fastestTime").text(0);
    } else {
      $("#fastestTime").text(fastestTime);
    }
    if (Cookies.get("cookieUserConsent") !== "true") {
      $("#cookies").css("visibility", "visible");
    }
    return $("#a, #b, #c, #d, #e, #f, #g, #h, #i, #j, #k, #l, #m, #n, #o, #p, #q, #r, #s, #t, #u, #v, #w, #x, #y, #z").click(function() {
      return chooseStart(this.innerHTML);
    });
  });

  timeBegan = null;

  timeStopped = null;

  stoppedDuration = 0;

  started = null;

  start = function() {
    if (timeBegan === null) {
      timeBegan = new Date();
    }
    if (timeStopped !== null) {
      stoppedDuration += new Date() - timeStopped;
    }
    return started = setInterval(clockRunning, 1);
  };

  stop = function() {
    timeStopped = new Date();
    return clearInterval(started);
  };

  clockRunning = function() {
    var currentTime, ms, sec, timeElapsed;
    currentTime = new Date();
    timeElapsed = new Date(currentTime - timeBegan - stoppedDuration);
    sec = timeElapsed.getUTCSeconds();
    ms = timeElapsed.getUTCMilliseconds();
    return $("#time").text(sec + "." + ms);
  };

  reset = function() {
    var currentChar, currentId, i, number, results;
    console.log("resetted");
    typedLetters = 0;
    typedWrongLetters = 0;
    clearInterval(started);
    stoppedDuration = 0;
    timeBegan = null;
    timeStopped = null;
    results = [];
    for (number = i = 1; i <= 26; number = ++i) {
      currentChar = String.fromCharCode(number + 96);
      currentId = "#" + currentChar;
      $(currentId).removeClass("correct");
      results.push($(currentId).removeClass("wrong"));
    }
    return results;
  };

  computeWPM = function() {
    var currentTime, wpm;
    currentTime = new Date();
    wpm = Math.floor(typedLetters * 1000 * 60 / (5 * new Date(currentTime - timeBegan)));
    return Math.min(400, wpm);
  };

  this.hideCookies = function() {
    Cookies.set("cookieUserConsent", "true");
    return $("#cookies").fadeOut();
  };

  chooseStart = function(a) {
    var currentChar, currentId, i, index, j, number, ref;
    stop();
    reset();
    for (number = i = 1; i <= 26; number = ++i) {
      currentChar = String.fromCharCode(number + 96);
      currentId = "#" + currentChar;
      $(currentId).removeClass("inactive");
    }
    $("#fastestTime").removeClass("inactive");
    index = a.charCodeAt(0) - 96;
    if (index !== 1) {
      $("#fastestTime").addClass("inactive");
      for (number = j = 1, ref = index - 1; 1 <= ref ? j <= ref : j >= ref; number = 1 <= ref ? ++j : --j) {
        currentChar = String.fromCharCode(number + 96);
        currentId = "#" + currentChar;
        $(currentId).addClass("inactive");
      }
    }
    numberOfStartingLetters = index - 1;
    return console.log(numberOfStartingLetters);
  };

}).call(this);
