// Generated by CoffeeScript 1.12.2
(function() {
  var advanceChar, atoz, clockRunning, computeWPM, fastestTime, reset, start, started, stop, stoppedDuration, timeBegan, timeStopped, typedLetters;

  typedLetters = 0;

  atoz = "abcdefghijklmnopqrstuvwxyz";

  if ((Cookies.get("time") != null)) {
    fastestTime = Cookies.get("time");
  } else {
    fastestTime = "";
  }

  advanceChar = function(char) {
    var currentTyped, nextCharacter;
    if (char - 97 === typedLetters) {
      nextCharacter = String.fromCharCode(char);
      currentTyped = $("#typed").text();
      $("#typeHere").html('<span id="typed">' + currentTyped + nextCharacter + '</span>' + atoz.substring(typedLetters + 1, 26));
      console.log('yes');
      typedLetters++;
      if (typedLetters === 26) {
        stop();
        if (fastestTime.length !== 0) {
          fastestTime = Math.min(fastestTime, $("#time").text());
        } else {
          fastestTime = $("#time").text();
        }
        document.cookie = "time=" + fastestTime;
        $("#fastestTime").text(fastestTime);
      }
      return $("#speed").text(computeWPM());
    } else {
      return console.log('no');
    }
  };

  $(document).keypress(function(e) {
    if (e.which === 13) {
      return reset();
    } else if (typedLetters === 26) {

    } else {
      if (typedLetters === 0) {
        reset();
        start();
      }
      return advanceChar(e.which);
    }
  });

  $(function() {
    $("#reset").click(function() {
      return reset();
    });
    if (fastestTime.length === 0) {
      $("#fastestTime").text(0);
    } else {
      $("#fastestTime").text(fastestTime);
    }
    if (Cookies.get("cookieUserConsent") !== "true") {
      return $("#cookies").css("visibility", "visible");
    }
  });

  timeBegan = null;

  timeStopped = null;

  stoppedDuration = 0;

  started = null;

  start = function() {
    if (timeBegan === null) {
      timeBegan = new Date();
    }
    if (timeStopped !== null) {
      stoppedDuration += new Date() - timeStopped;
    }
    return started = setInterval(clockRunning, 1);
  };

  stop = function() {
    timeStopped = new Date();
    return clearInterval(started);
  };

  clockRunning = function() {
    var currentTime, ms, sec, timeElapsed;
    currentTime = new Date();
    timeElapsed = new Date(currentTime - timeBegan - stoppedDuration);
    sec = timeElapsed.getUTCSeconds();
    ms = timeElapsed.getUTCMilliseconds();
    return $("#time").text(sec + "." + ms);
  };

  reset = function() {
    console.log("resetted");
    $("#typeHere").html('<span id="typed"></span>' + atoz);
    typedLetters = 0;
    clearInterval(started);
    stoppedDuration = 0;
    timeBegan = null;
    return timeStopped = null;
  };

  computeWPM = function() {
    var currentTime;
    currentTime = new Date();
    return Math.min(400, Math.floor((typedLetters * 1000 * 60 / 5) / (new Date(currentTime - timeBegan))));
  };

  this.hideCookies = function() {
    Cookies.set("cookieUserConsent", "true");
    return $("#cookies").fadeOut();
  };

}).call(this);
